#!/usr/bin/env python3
"""
pass_a_metadata.py - TOC Metadata Extraction (Pass A)
=====================================================

Extracts structured metadata from TOC elements generated by Unstructured.io.
Builds hierarchical structure, categories, and term index.
Can integrate with Gate 0 marker files for document linkage.

Usage:
  pass_a_metadata.py <elements_json> [options]
  pass_a_metadata.py -v | --version
  pass_a_metadata.py -? | --help

Arguments:
  elements_json      Path to elements JSON from pass_a_unstructured

Options:
  -o, --output DIR       Output directory (default: same as input)
  -s, --system STR       Game system (PF1E|PF2E|DND5E|auto) (default: auto)
  -p, --publisher STR    Publisher name (default: auto-detect)
  --gate-marker FILE     Gate 0 marker file for document metadata linkage
  -v, --version          Show version
  -?, --help             Show this help

Examples:
  # Basic extraction
  pass_a_metadata.py /Transfer_Station/Pass_A_Out/manual_toc_elements.json

  # With Gate 0 marker integration
  pass_a_metadata.py /Transfer_Station/Pass_A_Out/manual_toc_elements.json \
    --gate-marker /Transfer_Station/Gate_0_Out/manual_20251009_120000.json

  # With custom system
  pass_a_metadata.py /Transfer_Station/Pass_A_Out/manual_elements.json --system PF2E

Version: 2.0.0
Author: n8n TTRPG Center
"""

import argparse
import json
import re
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Tuple, Optional


__version__ = "2.0.0"


class MetadataExtractorError(Exception):
    """Base exception for metadata extractor errors."""
    pass


def load_gate_marker(marker_path: Path) -> Optional[Dict[str, Any]]:
    """
    Load and validate Gate 0 marker file.

    Args:
        marker_path: Path to Gate 0 marker file

    Returns:
        Parsed marker data or None if invalid

    Raises:
        MetadataExtractorError: If marker file cannot be read or is invalid
    """
    if not marker_path.exists():
        raise MetadataExtractorError(f"Gate marker file not found: {marker_path}")

    try:
        with open(marker_path, 'r', encoding='utf-8') as f:
            marker_data = json.load(f)
    except json.JSONDecodeError as e:
        raise MetadataExtractorError(f"Invalid JSON in gate marker: {e}")
    except IOError as e:
        raise MetadataExtractorError(f"Failed to read gate marker: {e}")

    # Validate required fields (from gate_0_hash.py)
    required_fields = ['document_id', 'original_filename', 'sha256_hash']
    missing_fields = [field for field in required_fields if field not in marker_data]

    if missing_fields:
        raise MetadataExtractorError(
            f"Gate marker missing required fields: {', '.join(missing_fields)}\n"
            f"This file was not created by gate_0_hash.py"
        )

    return marker_data


class TOCMetadataExtractor:
    """Extract structured metadata from TOC elements."""

    # Game system detection patterns
    SYSTEM_PATTERNS = {
        'PF1E': [r'pathfinder\s+(?:roleplaying\s+game|rpg)', r'paizo\s+publishing', r'3\.5\s+compatible'],
        'PF2E': [r'pathfinder\s+(?:second\s+edition|2e)', r'pathfinder\s+core\s+rulebook\s+(?:2nd|second)'],
        'DND5E': [r'd&d\s+5(?:th|e)', r'dungeons?\s+(?:and|&)\s+dragons?\s+5', r'wizards\s+of\s+the\s+coast'],
        'STARFINDER': [r'starfinder'],
        'CALL_OF_CTHULHU': [r'call\s+of\s+cthulhu', r'chaosium'],
    }

    # Common TOC category patterns
    CATEGORY_PATTERNS = {
        'character_creation': [r'character', r'races?', r'classes?', r'backgrounds?', r'ancestr(?:y|ies)'],
        'combat': [r'combat', r'weapons?', r'armor', r'actions?', r'fighting'],
        'magic': [r'magic', r'spells?', r'rituals?', r'casting', r'arcane'],
        'equipment': [r'equipment', r'gear', r'items?', r'treasure'],
        'rules': [r'rules', r'mechanics', r'gameplay'],
        'setting': [r'setting', r'world', r'lore', r'history'],
        'game_master': [r'(?:game\s+master|gm|dm)', r'running', r'adventures?'],
    }

    def __init__(self, elements: List[Dict[str, Any]]):
        self.elements = elements
        self.titles = [e for e in elements if e.get('type') == 'Title']

    def detect_hierarchy_level(self, title_element: Dict[str, Any], context_titles: List[Dict[str, Any]]) -> int:
        """
        Detect hierarchy level (1-3) based on text patterns and coordinates.

        Args:
            title_element: The title element to classify
            context_titles: Surrounding title elements for context

        Returns:
            Hierarchy level (1=chapter, 2=section, 3=subsection)
        """
        text = title_element.get('text', '').strip()

        # Level 1 indicators: All caps, chapter keywords, "Part", major divisions
        if (text.isupper() and len(text) > 5) or \
           re.search(r'^(?:CHAPTER|PART|BOOK|APPENDIX|INDEX)\s+\d+', text, re.I):
            return 1

        # Level 2 indicators: Title case, section numbers
        if re.search(r'^\d+\.\d+\s+\w+', text) or \
           (text.istitle() and not text.isupper()):
            return 2

        # Level 3 indicators: Subsection patterns
        if re.search(r'^\d+\.\d+\.\d+\s+\w+', text):
            return 3

        # Default to level 2 for ambiguous cases
        return 2

    def build_toc_structure(self) -> List[Dict[str, Any]]:
        """
        Build hierarchical TOC structure from title elements.

        Returns:
            List of TOC entries with hierarchy information
        """
        toc_structure = []
        current_chapter = None

        for i, title in enumerate(self.titles):
            text = title.get('text', '').strip()
            page_num = title.get('metadata', {}).get('page_number', 0)

            # Detect hierarchy level
            level = self.detect_hierarchy_level(title, self.titles)

            # Build TOC entry
            entry = {
                'level': level,
                'title': text,
                'page_start': page_num,
                'page_end': None,  # Will be set by next entry
                'category': self._classify_category(text),
            }

            # Set page_end for previous entry
            if toc_structure:
                toc_structure[-1]['page_end'] = max(page_num - 1, toc_structure[-1]['page_start'])

            toc_structure.append(entry)

            # Track chapters for subcategory association
            if level == 1:
                current_chapter = text

        return toc_structure

    def _classify_category(self, title_text: str) -> str:
        """Classify a title into a category based on keywords."""
        text_lower = title_text.lower()

        for category, patterns in self.CATEGORY_PATTERNS.items():
            for pattern in patterns:
                if re.search(pattern, text_lower):
                    return category

        return 'other'

    def extract_categories(self, toc_structure: List[Dict[str, Any]]) -> Dict[str, List[str]]:
        """
        Extract category hierarchy from TOC structure.

        Args:
            toc_structure: Hierarchical TOC structure

        Returns:
            Dict mapping main categories to subcategories
        """
        categories = defaultdict(list)
        current_main = None

        for entry in toc_structure:
            category = entry['category']
            title = entry['title']

            if entry['level'] == 1:
                current_main = category
                if category not in categories:
                    categories[category] = []
            elif entry['level'] == 2 and current_main:
                if title not in categories[current_main]:
                    categories[current_main].append(title)

        return dict(categories)

    def extract_terms(self) -> List[Dict[str, Any]]:
        """
        Extract important terms and their page references.

        Returns:
            List of term entries with page references
        """
        terms = defaultdict(lambda: {'pages': set(), 'category': None})

        # Extract from titles
        for title in self.titles:
            text = title.get('text', '').strip()
            page_num = title.get('metadata', {}).get('page_number')

            if page_num:
                # Extract individual words (potential terms)
                words = re.findall(r'\b[A-Z][a-z]+(?:\s+[A-Z][a-z]+)*\b', text)
                for word in words:
                    if len(word) > 3:  # Skip short words
                        terms[word]['pages'].add(page_num)
                        if not terms[word]['category']:
                            terms[word]['category'] = self._classify_category(text)

        # Convert to list format
        term_list = []
        for term, data in sorted(terms.items()):
            term_list.append({
                'term': term,
                'category': data['category'],
                'page_references': sorted(list(data['pages']))
            })

        return term_list

    def detect_game_system(self) -> Optional[str]:
        """
        Auto-detect game system from element text.

        Returns:
            Detected system code or None
        """
        # Combine all text for analysis
        all_text = ' '.join(e.get('text', '') for e in self.elements[:50])  # First 50 elements
        all_text_lower = all_text.lower()

        # Check each system pattern
        for system, patterns in self.SYSTEM_PATTERNS.items():
            for pattern in patterns:
                if re.search(pattern, all_text_lower):
                    return system

        return None

    def detect_publisher(self) -> Optional[str]:
        """
        Auto-detect publisher from element text.

        Returns:
            Detected publisher name or None
        """
        # Common publishers
        publishers = ['Paizo', 'Wizards of the Coast', 'Chaosium', 'Monte Cook Games', 'Green Ronin']

        all_text = ' '.join(e.get('text', '') for e in self.elements[:50])

        for publisher in publishers:
            if re.search(publisher, all_text, re.I):
                return publisher

        return None


def process_metadata(
    elements_path: Path,
    output_dir: Optional[Path] = None,
    game_system: str = "auto",
    publisher: str = "auto",
    gate_marker_path: Optional[Path] = None
) -> Dict[str, Any]:
    """
    Extract metadata from elements JSON.

    Args:
        elements_path: Path to elements JSON file
        output_dir: Output directory (default: same as input)
        game_system: Game system code or 'auto' for detection
        publisher: Publisher name or 'auto' for detection
        gate_marker_path: Optional path to Gate 0 marker file

    Returns:
        Dict with metadata

    Raises:
        MetadataExtractorError: If processing fails
    """
    # Load elements
    try:
        with open(elements_path, 'r', encoding='utf-8') as f:
            elements = json.load(f)
    except (IOError, json.JSONDecodeError) as e:
        raise MetadataExtractorError(f"Failed to load elements JSON: {e}")

    if not isinstance(elements, list):
        raise MetadataExtractorError(f"Expected list of elements, got {type(elements)}")

    # Create extractor
    extractor = TOCMetadataExtractor(elements)

    # Auto-detect system and publisher if requested
    if game_system == "auto":
        detected_system = extractor.detect_game_system()
        game_system = detected_system or "UNKNOWN"

    if publisher == "auto":
        detected_publisher = extractor.detect_publisher()
        publisher = detected_publisher or "Unknown"

    # Build TOC structure
    toc_structure = extractor.build_toc_structure()

    # Extract categories
    categories = extractor.extract_categories(toc_structure)

    # Extract terms
    terms = extractor.extract_terms()

    # Load Gate 0 marker if provided
    gate_marker = None
    document_id = elements_path.stem.replace('_elements', '').replace('_toc', '')

    if gate_marker_path:
        gate_marker = load_gate_marker(gate_marker_path)
        document_id = gate_marker['document_id']

        # Add document_id to all terms
        for term in terms:
            term['document_id'] = document_id

    # Build metadata
    if gate_marker:
        # New structure with Gate 0 integration
        metadata = {
            'document': {
                'document_id': gate_marker['document_id'],
                'original_filename': gate_marker['original_filename'],
                'original_path': gate_marker.get('original_path'),
                'file_size_bytes': gate_marker.get('file_size_bytes'),
                'sha256_hash': gate_marker['sha256_hash'],
                'computed_at': gate_marker.get('computed_at'),
                'splits': gate_marker.get('splits', [])
            },
            'extraction': {
                'system': game_system,
                'publisher': publisher,
                'extraction_date': datetime.utcnow().isoformat() + 'Z'
            },
            'toc_structure': toc_structure,
            'categories': categories,
            'terms': terms,
            'statistics': {
                'total_elements': len(elements),
                'title_elements': len(extractor.titles),
                'toc_entries': len(toc_structure),
                'categories': len(categories),
                'terms': len(terms)
            }
        }
    else:
        # Legacy structure (backward compatible)
        metadata = {
            'document_id': document_id,
            'filename': elements_path.stem.replace('_elements', '').replace('_toc', ''),
            'system': game_system,
            'publisher': publisher,
            'extraction_date': datetime.utcnow().isoformat() + 'Z',
            'toc_structure': toc_structure,
            'categories': categories,
            'terms': terms,
            'statistics': {
                'total_elements': len(elements),
                'title_elements': len(extractor.titles),
                'toc_entries': len(toc_structure),
                'categories': len(categories),
                'terms': len(terms)
            }
        }

    # Determine output path
    if not output_dir:
        output_dir = elements_path.parent

    output_filename = f"{elements_path.stem.replace('_elements', '')}_metadata.json"
    output_path = output_dir / output_filename

    # Save metadata
    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(metadata, f, indent=2, ensure_ascii=False)
    except IOError as e:
        raise MetadataExtractorError(f"Failed to write metadata: {e}")

    return {
        'input_file': str(elements_path),
        'output_file': str(output_path),
        'metadata': metadata
    }


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description='Extract metadata from TOC elements',
        add_help=False
    )

    parser.add_argument(
        'elements_json',
        nargs='?',
        type=Path,
        help='Path to elements JSON from pass_a_unstructured'
    )
    parser.add_argument(
        '-o', '--output',
        type=Path,
        help='Output directory (default: same as input)'
    )
    parser.add_argument(
        '-s', '--system',
        type=str,
        default='auto',
        help='Game system (PF1E|PF2E|DND5E|auto) (default: auto)'
    )
    parser.add_argument(
        '-p', '--publisher',
        type=str,
        default='auto',
        help='Publisher name (default: auto-detect)'
    )
    parser.add_argument(
        '--gate-marker',
        type=Path,
        metavar='FILE',
        help='Gate 0 marker file for document metadata linkage'
    )
    parser.add_argument(
        '-v', '--version',
        action='version',
        version=f'pass_a_metadata v{__version__}'
    )
    parser.add_argument(
        '-?', '--help',
        action='help',
        help='Show this help message and exit'
    )

    args = parser.parse_args()

    if not args.elements_json:
        parser.print_help()
        sys.exit(1)

    return args


def main() -> int:
    """Main entry point."""
    try:
        args = parse_args()

        # Process metadata
        result = process_metadata(
            elements_path=args.elements_json,
            output_dir=args.output,
            game_system=args.system,
            publisher=args.publisher,
            gate_marker_path=args.gate_marker
        )

        metadata = result['metadata']

        # Success message (handle both old and new structures)
        if 'document' in metadata:
            # New structure with Gate 0 integration
            doc_id = metadata['document']['document_id']
            system = metadata['extraction']['system']
            publisher = metadata['extraction']['publisher']
        else:
            # Legacy structure
            doc_id = metadata['document_id']
            system = metadata['system']
            publisher = metadata['publisher']

        print(
            f"Metadata extracted for {doc_id}:\n"
            f"  System: {system}\n"
            f"  Publisher: {publisher}\n"
            f"  TOC entries: {metadata['statistics']['toc_entries']}\n"
            f"  Categories: {metadata['statistics']['categories']}\n"
            f"  Terms: {metadata['statistics']['terms']}\n"
            f"  Output: {Path(result['output_file']).name}"
        )

        return 0

    except MetadataExtractorError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("\nOperation cancelled by user", file=sys.stderr)
        return 130
    except Exception as e:
        print(f"Unexpected error: {e}", file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
