#!/usr/bin/env python3
"""
pass_a_metadata_worker.py - Async Worker for Pass A Metadata Extraction
========================================================================

Async worker that wraps pass_a_metadata.py to extract structured metadata
from TOC elements generated by Unstructured.io.

Usage:
    python pass_a_metadata_worker.py [options]

Options:
    --jobs-dir DIR         Root directory for job queues
    --log-dir DIR          Directory for worker logs
    --poll-interval SECS   Seconds between queue polls (default: 5)
    --log-level LEVEL      Logging level (DEBUG|INFO|WARNING|ERROR)
    --once                 Process one job and exit (for testing)
"""

import subprocess
import sys
from pathlib import Path
from typing import Any, Dict

from async_worker_base import AsyncWorkerBase
from path_utils import resolve_transfer_path


class PassAMetadataWorker(AsyncWorkerBase):
    """Async worker for Pass A metadata extraction."""

    stage_name = "pass_a_metadata"

    def _process_job(self, job_dir: Path, status: Dict[str, Any]) -> bool:
        """
        Process Pass A metadata extraction for a job.

        Args:
            job_dir: Path to job directory
            status: Current job status dict

        Returns:
            True if processing succeeded, False otherwise
        """
        try:
            # Get required file paths from status
            elements_file = status.get("pass_a_unstructured_output")
            if not elements_file:
                self.logger.error(f"Job {job_dir.name} missing pass_a_unstructured_output path")
                return False

            elements_path = Path(elements_file)
            if not elements_path.exists():
                self.logger.error(f"Elements file not found: {elements_path}")
                return False

            # Determine output directory (same as elements file location)
            output_dir = elements_path.parent

            # Build command for pass_a_metadata.py
            script_path = Path(__file__).parent / "pass_a_metadata.py"

            cmd = [
                sys.executable,
                str(script_path),
                str(elements_path),
                "--output", str(output_dir)
            ]

            # Add gate marker if available
            gate_marker = status.get("gate_0_marker_file")
            if gate_marker and Path(gate_marker).exists():
                cmd.extend(["--gate-marker", str(gate_marker)])

            self.logger.info(f"Running: {' '.join(cmd)}")

            # Execute pass_a_metadata.py
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=False,
                timeout=300  # 5 minute timeout
            )

            # Log output
            if result.stdout:
                self.logger.debug(f"STDOUT:\n{result.stdout}")
            if result.stderr:
                self.logger.warning(f"STDERR:\n{result.stderr}")

            if result.returncode != 0:
                self.logger.error(f"pass_a_metadata.py failed with exit code {result.returncode}")
                # Update status with error
                from async_job_utils import add_error, write_json_atomic, get_job_status_path
                status = add_error(status, f"pass_a_metadata.py exit code {result.returncode}")
                write_json_atomic(get_job_status_path(job_dir), status)
                return False

            # Determine metadata file path
            metadata_filename = elements_path.stem.replace("_elements", "") + "_metadata.json"
            metadata_path = output_dir / metadata_filename

            if not metadata_path.exists():
                self.logger.error(f"Metadata file not created: {metadata_path}")
                return False

            # Update job status with metadata file path
            from async_job_utils import write_json_atomic, get_job_status_path
            status["pass_a_metadata_output"] = str(metadata_path)
            status["metadata_extracted"] = True
            write_json_atomic(get_job_status_path(job_dir), status)

            self.logger.info(f"Metadata extraction completed: {metadata_path.name}")
            return True

        except subprocess.TimeoutExpired:
            self.logger.error(f"pass_a_metadata.py timed out after 5 minutes")
            return False
        except Exception as e:
            self.logger.exception(f"Unexpected error in metadata extraction: {e}")
            return False


if __name__ == "__main__":
    PassAMetadataWorker.main()
