version: '3.8'

networks:
  ttrpg-dev-net:
    driver: bridge
    name: ttrpg-dev-net

volumes:
  pg_data_dev:
    name: ttrpg_pg_data_dev
  mongo_data_dev:
    name: ttrpg_mongo_data_dev
  neo4j_data_dev:
    name: ttrpg_neo4j_data_dev
  redis_data_dev:
    name: ttrpg_redis_data_dev
  logs_dev:
    name: ttrpg_logs_dev
  uploads_dev:
    name: ttrpg_uploads_dev

services:
  app-dev:
    build: 
      context: .
      dockerfile: services/app/Dockerfile
      target: production
    container_name: ttrpg-app-dev
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
      - PORT=8000
      # Database connections
      - POSTGRES_HOST=postgres-dev
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ttrpg_dev
      - POSTGRES_USER=${POSTGRES_USER:-ttrpg_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ttrpg_dev_pass}
      - MONGO_URI=mongodb://mongo-dev:27017/ttrpg_dev
      - NEO4J_URI=bolt://neo4j-dev:7687
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-dev_password}
      - REDIS_URL=redis://redis-dev:6379/0
      # External services (unchanged)
      - ASTRA_DB_API_ENDPOINT=${ASTRA_DB_API_ENDPOINT}
      - ASTRA_DB_APPLICATION_TOKEN=${ASTRA_DB_APPLICATION_TOKEN}
      - ASTRA_DB_ID=${ASTRA_DB_ID}
      - ASTRA_DB_KEYSPACE=${ASTRA_DB_KEYSPACE:-default_keyspace}
      - ASTRA_DB_REGION=${ASTRA_DB_REGION:-us-east-2}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # Security
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      # Application settings
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-0}
      - ARTIFACTS_PATH=/app/artifacts
    volumes:
      - logs_dev:/var/log/ttrpg
      - uploads_dev:/data/uploads
      - ./artifacts/dev:/app/artifacts
    networks:
      - ttrpg-dev-net
    depends_on:
      postgres-dev:
        condition: service_healthy
      mongo-dev:
        condition: service_healthy
      neo4j-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: on-failure:3
    
  postgres-dev:
    image: postgres:16-alpine
    container_name: ttrpg-postgres-dev
    environment:
      - POSTGRES_DB=ttrpg_dev
      - POSTGRES_USER=${POSTGRES_USER:-ttrpg_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ttrpg_dev_pass}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    networks:
      - ttrpg-dev-net
    ports:
      - "5432:5432" # Exposed for admin tools
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ttrpg_user} -d ttrpg_dev"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  mongo-dev:
    image: mongo:7-jammy
    container_name: ttrpg-mongo-dev
    environment:
      - MONGO_INITDB_DATABASE=ttrpg_dev
    volumes:
      - mongo_data_dev:/data/db
    networks:
      - ttrpg-dev-net
    ports:
      - "27017:27017" # Exposed for admin tools
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  neo4j-dev:
    image: neo4j:5.23-community
    container_name: ttrpg-neo4j-dev
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-dev_password}
      - NEO4J_dbms_default__database=ttrpg_dev
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=512m
    volumes:
      - neo4j_data_dev:/data
    networks:
      - ttrpg-dev-net
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "${NEO4J_USER:-neo4j}", "-p", "${NEO4J_PASSWORD:-dev_password}", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  redis-dev:
    image: redis:7-alpine
    container_name: ttrpg-redis-dev
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data_dev:/data
    networks:
      - ttrpg-dev-net
    ports:
      - "6379:6379" # Exposed for admin tools
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true