"""Add source ingestion history table for SHA-based Pass C bypass

Revision ID: 6b44a9700b4d
Revises: 9a737c30cd2d
Create Date: 2025-09-12 08:03:14.099407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b44a9700b4d'
down_revision: Union[str, Sequence[str], None] = '9a737c30cd2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_ingestion_history',
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('last_processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('environment', sa.String(length=10), nullable=False),
    sa.Column('pass_c_artifacts_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('source_hash')
    )
    op.create_index('idx_ingestion_environment', 'source_ingestion_history', ['environment'], unique=False)
    op.create_index('idx_ingestion_processed_at', 'source_ingestion_history', ['last_processed_at'], unique=False)
    op.create_index('idx_ingestion_source_path', 'source_ingestion_history', ['source_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ingestion_source_path', table_name='source_ingestion_history')
    op.drop_index('idx_ingestion_processed_at', table_name='source_ingestion_history')
    op.drop_index('idx_ingestion_environment', table_name='source_ingestion_history')
    op.drop_table('source_ingestion_history')
    # ### end Alembic commands ###
