from pathlib import Path

path = Path("src_common/pass_b_logical_splitter.py")
text = path.read_text()
old = "        if not split_plan and self.section_catalog:\n            for section in self.section_catalog:\n                split_plan.append(\n                    {\n                        \"part_id\": None,\n                        \"page_start\": section[\"page_start\"],\n                        \"page_end\": section[\"page_end\"],\n                        \"section_id\": section.get(\"section_id\"),\n                        \"section_title\": section.get(\"title\"),\n                    }\n                )\n\n            logger.info(\n                \"pass_b_section_catalog_applied\",\n                extra={\n                    \"job_id\": self.job_id,\n                    \"sections\": len(self.section_catalog),\n                    \"mode\": mode,\n                },\n            )\n            self._log_job(\n                \"Pass B section catalog reused: sections=\"\n                f\"{len(self.section_catalog)}, mode={mode}\"\n            )\n\n        split_index_path = pass_dir / \"split_index.json\"\n"
new = "        if not split_plan and self.section_catalog:\n            for section in self.section_catalog:\n                split_plan.append(\n                    {\n                        \"part_id\": None,\n                        \"page_start\": section[\"page_start\"],\n                        \"page_end\": section[\"page_end\"],\n                        \"section_id\": f\"pages-{section['page_start']}-{section['page_end']}\",\n                        \"section_title\": None,\n                    }\n                )\n\n            logger.info(\n                \"pass_b_section_catalog_applied\",\n                extra={\n                    \"job_id\": self.job_id,\n                    \"sections\": len(self.section_catalog),\n                    \"mode\": mode,\n                },\n            )\n            self._log_job(\n                \"Pass B section catalog reused: sections=\"\n                f\"{len(self.section_catalog)}, mode={mode}\"\n            )\n\n        split_index_path = pass_dir / \"split_index.json\"\n"
if old not in text:
    raise SystemExit("fallback block not found")
text = text.replace(old, new)
path.write_text(text)
