# Local Deployment (Self-Hosted Runner)

name: Deploy Local (DEV)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version to deploy (e.g., 1.2.3)'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ttrpg/app

jobs:
  deploy-dev-local:
    name: Deploy to DEV (local)
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull application image
      run: |
        APP_IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}"
        echo "APP_IMAGE=${APP_IMAGE}" >> $GITHUB_ENV
        docker pull "${APP_IMAGE}"

    - name: Deploy with docker compose (override image)
      env:
        APP_IMAGE: ${{ env.APP_IMAGE }}
      run: |
        export APP_IMAGE
        docker compose -f docker-compose.dev.yml -f docker-compose.release.override.yml up -d

    - name: Post-deploy health check
      run: |
        sleep 10
        curl -f http://localhost:8000/healthz
